api = input ("Enter Text Here")
print("Enter Text Here" + api +"Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here" + api + "Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
print("Enter Text Here")
 
